# Server config
server:
  port: 8080

# DB config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gamsungdb_jg
    username: betagamsung
    password: betagamsung

# MyBatis Framework config
mybatis:
  mapper-locations: mapper/*.xml